version: '3'
services:
  whoisondutytoday:
    image: whoisondutytoday:0.6.7
    restart: always
    container_name: whoisondutytoday
    build: .
    volumes:
      - /opt/whoisondutytoday/db/data/:/myapp/db/data/
    ports:
      - "3000:3000"
    env_file:
      - production.env.example
    logging:
      driver: "json-file"
      options:
        max-size: "2048k"
        max-file: "10"