---
- hosts: all
  become: yes
  user: vagrant
  vars:
    timezone: UTC
    RUBY_VERSION: 2.6.3
  tasks:
    - name: Set timezone to {{ timezone }}
      timezone:
        name: "{{ timezone }}"

    - name: Selinux set permissive mode
      selinux:
        policy: targeted
        state: permissive

    - name: Install Ruby
      shell: |
        setenforce 0
        update-ca-trust enable; update-ca-trust extract
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum makecache fast
        yum -y install epel-release
        yum -y install docker-ce docker-compose git unzip zip nodejs
        systemctl enable docker
        systemctl start docker
        gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
        curl -sSL https://rvm.io/mpapis.asc | gpg --import -
        curl -L get.rvm.io | bash -s stable
        source /etc/profile.d/rvm.sh
        rvm reload
        rvm requirements run
        rvm install {{ RUBY_VERSION }}
        rvm use {{ RUBY_VERSION }} --default
        gem install bundle
      args:
        executable: /bin/bash