require_relative 'action_create'
require_relative 'action_delete'
require_relative 'action_show_problems'
require_relative 'action_show_action'
require_relative 'answer_delete_custom_text'
require_relative 'answer_disable_hide_reason'
require_relative 'answer_enable_hide_reason'
require_relative 'answer_set_custom_text'
require_relative 'call_duty_person'
require_relative 'checked'
require_relative 'create_duty_for_user'
require_relative 'duty_create'
require_relative 'duty_delete'
require_relative 'duty_set_opsgenie_escalation'
require_relative 'duty_sync_with_opsgenie_schedule'
require_relative 'duty_update'
require_relative 'help'
require_relative 'i_am_on_duty'
require_relative 'my_status'
require_relative 'other'
require_relative 'unknown'
require_relative 'who_is_on_duty'
require_relative 'channel_labels_statistic'
require_relative 'channel_labels_list'
require_relative 'channel_labels_merge'
require_relative 'channel_reminder'
require_relative 'channel_tag_reporter_in_thread'
require_relative 'channel_auto_answer'
require_relative 'thread_labels_clean'
require_relative 'thread_labels'
require_relative 'git_commits'

module WhoIsOnDutyTodaySlackBotModule
  module Commands
  end
end